.travis.yml
Dockerfile

This change adds a Travis config file. This can be used to trigger CI builds on travis-ci.org. 
It also changes the Docker config to not upgrade packages from the distro baseline by default, to speed up the build.

Travis CI config for VirtualAgc

---

yaAGC/agc_engine.c

Fixes a problem with #46. Channel 13 should be written with the masked contents of channel 13, *not* of TIME6...

#46: Correct clearing of CH13's TIME6 enable bit on T6RUPT

---

yaAGC/agc_engine.c

This changes agc_engine to behave similarly to the hardware sim in this particular case of divide. This has the potential to fix #52, as in isolated test cases, a requested 77777 gimbal angle triggers 401 alarms in yaAGC, but not in the hardware sim.
I've got no detailed analysis to suggest that this should be the case this time around... just the statement that this is the apparent current behavior of the hardware sim (which very well could be wrong. I don't trust my DV anywhere near enough to say with certainty that it is wired correctly). The divide case makes plentiful use of WHOMP, which isn't documented in AGC4 Memo *#*9 and makes control pulse analysis even more of a pain than in non-WHOMP-using DVs.
Somewhat even more frighteningly, this PR contains no changes to Validation, …

yaAGC: Added a special case to DV (Dividend = 0, Divisor != 0)

---

Dockerfile
Dockerfile.dev

This uses a base Ubuntu 16.04 image with all packages installed on DockerHub to speed up builds.

Change Docker recipes to use my base image on hub.docker.com.

---

Validation/ValidateDV.agc
yaAGC/agc_engine.c

Welp... the control pulse study I did for #53 ended up being useful. Because despite showing the changes were correct in all the cases studied on that PR... it made me realize that they were wrong in some others that I hadn't looked at. Namely, when the dividend is 77777,00000, and when the divisor is negative.
Since I'm now pretty confident in the sim's correctness when dividing 0 by things, I put together a little table of all combinations of +0s, -0s, and divisors:
00000,00000 / p = 00000,00000
77777,00000 / p = 00000,00000
00000,77777 / p = 77777,77777
77777,77777 / p = 77777,77777
00000,00000 / n = 77777,00000
77777,00000 / n = 77777,00000
00000,77777 / n = 00000,77777
77777,77777 / n = 00000,77777
There's two things to take away from that:
1. L never changes, so I should just leave …

Correct (again) signs when dividing 0 by a nonzero number

---

yaAGC/agc_engine.c

This is Gergo "[Massive Camel](https://code.google.com/archive/p/virtualagc/issues/26)"'s fix for #26. I posted a description of what's happening on the issue.
@indy91, this will almost certainly make the 1201s and 1202s go away -- the total CPU load is going to be greatly reduced. I gotta say, it's pretty friggin awesome that this ended up mattering for something, though. Especially since it resulted in those particular alarms!

#26: Correct cycle count for multi-MCT instructions

---

yaAGC/agc_cli.c
yaAGC/agc_cli.h
yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaAGC/agc_engine_init.c
yaAGC/agc_simulator.c

This adds emulation for the first of the ALGA alarms (#137), the Night Watchman. It should be very accurate to the behavior of the hardware. Once every 1.28s, it starts looking for accesses to NEWJOB (address 67). If that doesn't happen within 0.64s, a reset is triggered. The reset takes 2 MCTs to get to address 4000, going through the sequences GOJAM and TC 4000. CH77 bits are accrued as alarms are looked at, and then emitted all at the end if any alarms were tripped.
The alarms will always occur and will always update CH77, but their ability to cause a reset can be inhibited with the command-line option --inhibit-alarms. This functionality is exactly analogous to the AGC Monitor signal NHALGA. It's plumbed through in much the same way as DebugDsky.
I also noticed that counter interrupts …

Night Watchman emulation in yaAGC

---

yaAGC/agc_engine.c
yaAGC/agc_engine.h

Pretty straightforward, now that the framework is there. Aurora now trips the Rupt Lock rather than the Night Watchman, and thus breaks out of the 00 lockup just as quickly as the hardware sim. Finishes #137, I think, since we probably don't want to model any of the other possible alarms.

yaAGC: Added emulation of TC Trap and Rupt Lock alarms

---

Validation/SmallyDVCHECK.agc
Validation/SmallyDVCHK.agc
yaAGC/agc_engine.c

There were two separate problems with DV that Aurora caught:
1. When the dividend and divisor have the same magnitude, the remainder (L) should receive the quotient rather than the divisor. This had come up before as a difference between the hardware sim and yaAGC -- Aurora just confirmed the suspicion that yaAGC was incorrect.
2. Completely unexpectedly, the two cases "dividend == divisor" and "dividend == +-0" blend together when dividing 0 by 0. Like the former case, A receives posmax or negmax. And like the latter case, L remains unchanged (unlike in the former). This mish-mash of special cases was caught by the extensive arithmetic divide tests in DVCHECK.
With these corrections in place, Aurora passes both DVCHK (control pulses) and DVCHECK (extensive arithmetic) tests for the DV …

DV fixes based on Aurora tests

---

yaAGC/agc_engine.c

There were two things causing RUPTCHK to fail -- CCS was considering overflow condition *after* it did its diminished absolute value thing, rather than before, causing it to take the wrong branch.
The other problem was with interrupt handling. Most importantly, when the AGC takes an interrupt, Z has already been incremented _past_ the address the interrupt will be returning to by the previous instruction. RUPTCHK was using the value of ZRUPT inside the TIME3 ISR to make sure the interrupt interrupted exactly the right place, so that was off by one.
I've also changed the interrupt selection logic. It was previously a round-robin sort of thing, but the behavior of the hardware was much simpler. The interrupt vectors starting at 4000 were ordered in terms of their priority, and the highest …

yaAGC: CCS and interrupt fixes for RUPTCHK

---

assembly_language_manual.html

And some other random things that I know or was able to test in the hardware sim.
I hadn't thought of trying to access memory in bank 44 or higher, so I added that to Validation and took a look at what the hardware sim did. It wasn't very happy -- it still cycled the strands and strobed the fixed sense amplifiers, but didn't actually select any of the ropes or modules, so who knows what sort of nonsense it would have gotten back.
Anyways, my goal for this page is to one day remove all of the green text. I still need to add a section describing of all the hardware alarms, now that making them happy is required for successful program execution, and would like to move the description of all the non-fictitious I/O channels off of the developer page and onto this manual.
@rburkey2005, I didn't …

Language manual updates concerning changes made to yaAGC over the past weeks

---

yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaDSKY2/CM.ini
yaDSKY2/LM.ini
yaDSKY2/yaDSKY2.cpp
yaDSKY2/yaDSKY2.h

Here's the first batch of updates to yaAGC and yaDSKY2 to make DSKY handling a bit more realistic.
First, a gif of me testing the changes in Aurora (yes, I know it's a CM DSKY :P):
And a description of what's going on:
1. Computer is started, which lights RESTART
2. V35E is entered, which performs a light test. Because the RESTART light was active, it is not extinguished after the test.
3. The RESTART light is acknowledged with RSET and turns off.
4. V35E is reentered. RESTART turns on for the light test, but goes off after the end.
5. V01N10E 77E is entered to show the state of the hardware alarm latches. Because I started with a previously used Aurora core dump, it's all 0.
6. The control pulse self test is started with V21N27E 1E. This is on my master branch, and the RUPTCHK fixes are …

yaAGC+yaDSKY2: Updates to make DSKY handling more 'realistic'

---

Aurora12/DIGITAL_AUTOPILOT_ERASABLE.agc

just a quick fix to avoid an endless chain of errors when doing preliminary assemblies.

capitalize setloc. creates an endless chain of errors

---

.gitignore
Artemis072/Makefile
Aurora12/Makefile
Colossus249/Makefile
Comanche055/Makefile
Luminary099/Makefile
Luminary131/Makefile
Makefile.inc
Solarium055/Makefile
Sunburst120/Makefile

Change the flight builds to use a common make include file (`Makefile.inc` at top-level). 
- This means we can modify build rules in one place. 
- Differences in YUL options per-flight are specified using the `EXTRA_YUL_ARGS` variable, see `Solarium055` for an example.
- Added a `format` target. This reformats all the sources in a flight directory with `yaYUL --format`.

Use common Makefile

---

Makefile
Makefile.inc

Add a top-level `format-missions` target that reformats all AGC source using `yaYUL`.
Fixed Makefile.inc header comments.

Add format-missions target

---

Aurora12/Makefile
yaYUL/yaYUL.c

Option to stop `yaYUL` once syntax-checking is complete, and not attempt symbol resolution. This is intended for proofing. No listing is produced, syntax errors are printed.

Add --syntax to yaYUL

---

yaAGC/SocketAPI.c
yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaAGC/agc_engine_init.c
yaDSKY2/yaDSKY2.cpp

The only things that operates in standby mode, for the moment, are the scalers and the DSKY. I found while doing this that the HI SCALER and LOW SCALER input channels were incrementing too slowly  -- LOW SCALER should increment at 3200pps, not 1600pps. Since those channels are how the AGC determines how much time elapsed in standby mode, time appeared to move at half speed while the computer was in standby. As a side bonus of speeding them up, TIME6 finally has the right phasing.
Here's a little gif of the light test and standby mode in action:

yaAGC: Added support for standby mode

---

Borealis/AGC_BLOCK_TWO_EXTENDED_TESTS.agc
Borealis/ERASABLE_ASSIGNMENTS.agc
Borealis/FRESH_START_AND_RESTART.agc
yaAGC/agc_engine.c

This implements the quirks of Z/ZRUPT as described in #1048, and includes new tests in Borealis to exercise them. yaAGC seems happy, but I'd like to run the new Borealis on hardware before merging this in, to make sure everything works as I expect.

Improved handling of Z and ZRUPT

---

Borealis/AGC_BLOCK_TWO_EXTENDED_TESTS.agc
Borealis/Main.annotation
yaAGC/agc_engine.c

This implements a streamlined version of the code presented in #1047, plus implementation of the various other weirdnesses associated with DV discussed there.
* All cases where the divisor is smaller than the dividend (which result in "total nonsense") should now match results gotten on the original hardware.
* DV A, DV L, and DV Q all have special handling now to match "unexpected" modifications that happen to those registers before the divisor is sampled. All such cases I've tried match the hardware sim.
* Divisors with positive or negative overflow are also now handled by the new DV register simulation, since the overflow totally changes the results. Again, all the cases I have tried with overflow match the hardware sim.
All of the existing Aurora and Retread tests still pass, so I …

yaAGC: Added simulation of "total nonsense" in DV and other unexpected cases

---

piPeripheral/piDSKY.py
piPeripheral/piDSKY2.py
yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaDSKY/src/CM.ini
yaDSKY/src/LM.ini
yaDSKY/src/LM0.ini
yaDSKY/src/LM1.ini

In the AGC, the output to the TEMP light is a logical OR of channel 11 bit 4 (the output bit to turn on the light) and channel 30 bit 15 (the input bit from the IMU indicating its temperature is out of range). This was done so the light would still work in standby mode. This is apparently needed for the TEMP light to operate correctly in NASSP, since software appears to be lazy about maintaining the output bit.
These changes add a new bit to channel 163 that indicates what the current state of the TEMP light should be, and update all of our various DSKYs to use that instead of channel 11 bit 4.
@indy91, let me know if these changes make the TEMP light work correctly for you.

Channel 163 bit for TEMP

---

assembly_language_manual.html

The text here confused Wikipedia, leading to the wrong core rope size on the AGC page.

Explain core memory size.

---

Retread50/ERASABLE_ASSIGNMENTS.agc
Retread50/EXTENDED_VERBS_FOR_MODING.agc
Retread50/MAIN.agc
Retread50/Main.annotation
Retread50/VERB_AND_NOUN_INFORMATION.agc

I've decided to take a bit of a break from reconstruction and spend some time focusing on all of the rope modules we've dumped recently. To kick things off, I went back to Retread 50 and finished off the disassembly of the new stuff in bank 11. No more pesky UNKxxxx labels!
It turns out a lot of it was able to be correlated to various chunks of code in Aurora, just to a lesser extent than the stuff I already had done. The only thing that was still almost entirely different from other things we have was Verb 43, for gyro pulse torquing. To help with the disassembly, I created a flowchart of how it works (matching the MIT flowcharts style as closely as I could):
To use this verb, you apparently have to manually enter three double-precision numbers into location 1210 (which I've guessed was …

Retread 50: Completed disassembly of new extended verbs

---

CMakeLists.txt
yaAGC/CMakeLists.txt
yaAGC/agc_engine.h
yaDSKY2/CMakeLists.txt
yaYUL/CMakeLists.txt

added metadata to CMake so that existing targets are installable in user directory ~/VirtualAGC upon
```sh
cmake --build build --target install
```
for CMake, it's considered an anti-pattern to copy files outside the build directory without the command above.
So a fresh new user would do:
```sh
cmake -B build
cmake --build build --target install
```
to configure, compile and install from scratch

CMake install

---

yaAGC/agc_engine.h

We're doing some work on getting NASSP and virtualagc synced up again. See #622 
Visual Studio has deprecated functions linke scanf, strcat, strcpy, etc. because they can be dangerous if you don't know what you're doing. Of course we know what we're doing (right?) and want to keep portability with other OS' so we can safely disable this as we already have in NASSP.

Prevent compile warning in Visual Studio

---

CMakeLists.txt
Luminary099/CMakeLists.txt
Luminary099/Makefile
Tools/CMakeLists.txt
enet/CMakeLists.txt
yaAGC/CMakeLists.txt
yaAGS/CMakeLists.txt
yaASM/CMakeLists.txt
yaDSKY2/CMakeLists.txt
yaLEMAP/CMakeLists.txt
yaLVDC/CMakeLists.txt
yaLVDC/virtualWire.c
yaLVDC/yaLVDC.c
yaOBC/CMakeLists.txt
yaYUL/CMakeLists.txt

* skip yaDSKY2 if Wx not present
* handle time.h detection more correctly
* add yaLEMAP, yaOBC, yaAGS, Tools
* general project additions made since last CMake update
* add example target for Luminary099 using yaYUL
This was tested on GCC and Clang with MacOS, Windows, and Linux

CMake: corrections, add more targets

---

yaAGC/agc_cli.c
yaAGC/agc_cli.h
yaAGC/agc_simulator.c

By default yaAGC looks for a file called `core` to reload the state of the erasable from a previous run. This is done to mimic the behavior of the non-volatile erasable memory used in the AGC and as a convenient option to continue running the program at a later time. However I don't always want to resume with a previous memory state and start completely fresh instead. My workflow used to consist of:
1. Run yaAGC
2. Make a change and recompile the rope
3. Remove the core file
4. Run yaAGC again.
There are occasions where I make small changes to a rope in quick succession and having to remove the core file gets old very fast. Or one might for example want to do a fresh run and compare that to a saved state later.
This commit adds a new convenience option to yaAGC, `--no-resume`, which …

Added --no-resume cli option

---

README.md

Include the weight and dimensions of the AGC an DSKY in kilograms and cm (weight to 3.s.f. as given by imperial measurements) for people more accustomed to metric system

Add metric system units to readme

---

download.html

Last year, when these instructions were written, it was necessary to either compile wasi-sdk from a specific git commit, or wait until wasi-sdk version 13 was released.
Meanwhile, wasi-sdk is at version 16, so the version check and the compilation from source are no longer necessary. It is always possible to use the pre-built wasi-sdk release files.
This allows to simplify the WebAssembly build instructions.
The upgrade of wasi-sdk to version 16 makes it necessary to change the VirtualAGC WebAssembly compiler arguments, for which I will create a separate pull request to the master branch.

Simplify WebAssembly build instructions

---

README.md
yaAGC/Makefile

This is the pull request that should be merged together with https://github.com/virtualagc/virtualagc/pull/1182
To make the WebAssembly build more simple, I've made the optimization steps optional and simply mentioned them in the text.

Upgrade dependency wasi-sdk for WebAssembly builds

---

yaYUL/ParseXCADR.c
yaYUL/Pass.c

Here's a couple of corrections to yaYUL I've needed to make for my work-in-progress Sunrise 45 source reconstruction:
- Added support for the `LOC` pseudo-op to Block I
- Changed XCADR to behave like the original Yul
- Removed old XCADR-related workaround code for the symbol `DECON` in Solarium 55

yaYUL: Corrections required for Sunrise 45 assembly

---

yaYUL/Pass.c

Another interpretive opcode that only appears in Corona, as far as Block I ropes go. Plus the file changelog that I forgot for VXM*.

yaYUL: Added DOT* support for Block I

---

yaYUL/Pass.c

Same, familiar story -- Sunrise 69 uses TSU*, which is unused by all of our other Block I programs.

yaYUL: Added TSU* support for Block I

---

SundialE/AGC_BLOCK_TWO_SELF-CHECK.agc
SundialE/FRESH_START_AND_RESTART.agc
SundialE/IMU_MODE_SWITCHING_ROUTINES.agc
SundialE/LIST_PROCESSING_INTERPRETER.agc
SundialE/PINBALL_GAME__BUTTONS_AND_LIGHTS.agc
SundialE/SUM_CHECK_END_OF_BANK_MARKERS.agc
SundialE/SXTMARK.agc
SundialE/T4RUPT_PROGRAM.agc

While working on the Aurora 88 disassembly, I ran into what I briefly thought might have been a bug in yaYUL. In attempting to keep patches co-located with the code being patched, I created an inadvertent circular SETLOC chain, caused by the `SETLOC` for a patch in bank 13 preceding the first `BANK 13`  card in the listing. yaYUL gave up after 10 passes and produced no output.
I thought for a moment that perhaps the original Yul might be able to handle this situation, so I whipped up a punch card deck and threw it into pyul. It didn't even get as far as yaYUL did before barfing. The cuss it gave me, however, made me question some of what I had done in Sundial E.
So I put together a simple test program and fed it into both yaYUL and pyul:
```
BANK    10
ZERO        OCT     0
END1 …
```

Sundial E: disentangle illegally-placed patches

---

yaYUL/ParseEQUALS.c

Aurora 88 contains some placeholder code where it's pretty apparent that they inserted the desired opcodes, but didn't fill in the arguments which were not yet defined:
```
RESUME                  # HAND CONTROL RUPT   ***FIX LATER****
CA
XCH     BBANK
TCF
```
In the original Yul, any empty arguments like that evaluate to the current address. yaYUL already supports this for TC, TCF, and CADR, since those are specific cases that have appeared in other listings, but it currently throws errors for the CA. This change generalizes the handling of empty-string symbols, so they evaluate to the current address.
Running this code through both pyul and yaYUL now produces the following results:
```
BANK    10
LOC     +123
CS
CA
TS
AD
```
pyul gives:
```
0001                                  10,2000 …
```

yaYUL: Generalize treatment of empty arguments as referring to the current location

---

SundialE/PRELAUNCH_ALIGNMENT_PROGRAM.agc

Aurora 88 has a nearly-identical copy of this code, which has given me a means of cross-referencing some of the more mysterious things. This turned up two errors:
- What I thought was an unused constant is instead apparently an (unreferenced?) `TC GRABWAIT`.
- A place where I had used the label `WANGI` should instead apparently be `XSM1 +16D`. `WANGI` and `XSM1 +16D` share an address in Sundial E, but not in Aurora 88. The code is identical, as is the offset between XSM1 and the word in question, so `WANGI` must not be correct.

Sundial E: minor PRELAUNCH changes, based on Aurora 88 disassembly

---

yaLVDC/gdbInterface.c
yaLVDC/runOneInstruction.c

- The debug interface wasn't correctly accepting `SI` and `NI`
- CDS shouldn't require A8 to be 0:
- MPH was not automatically loading PQ into the accumulator. This is mechanized in the LVDC by forcing the instruction `CLA 775` to automatically occur 4 times after the `MPH` instruction. The last one grabs the final product.
- MPH and MPY were producing very bad results at first, and then mostly-correct-but-sometimes-off-by-one results once the gross error was fixed. I couldn't for the life of me find a reliable way to determine if the result was going to be off by one or not. But I did find that a naive implementation of the algorithm described in paragraph 2-319 of the laboratory maintenance instructions lead to results that match the simulator in every case I have thrown at it so far. …

yaLVDC: Assorted fixes for CDS, MPY/MPH, and debugging

---

yaLVDC/runOneInstruction.c

Throwing more test cases at my MPY implementation led me to discover it wasn't correctly handling negative multiplicands (negative multipliers were fine). This tweak fixes that.
The test cases I'm running it through are [here](https://github.com/thewonderidiot/lvdc_simulation/blob/f70e27eef1abb9d7f3f35358c32761f05b195e78/self-test/self-test.lvdc#L1010). This is a port of the PTC self-test program that I'm making for the LVDC. I expanded all of the applicable tests to try to more fully cover LVDC functionality, and am now starting to add test cases for MPY, MPH, DIV, and EXM. All of these MPH cases are passing now in both yaLVDC and my simulator.
The best "source of truth" I've found for a correct multiply result is this little chunk in the AS-512 software:
```
GP2291 CLA     775 …
```

yaLVDC: Correctly handle negative multiplicands for MPY/MPH

---

yaLVDC/runOneInstruction.c
yaLVDC/yaLVDC.h

* MPY and DIV continuously update PQR, making it unsuitable for temporary storage while they're in progress. I added a countdown tracking their progress, and changed runOneInstruction() to update PQR at the end of every cycle with results. Ongoing MPYs and DIVs also inhibit interrupts from the LVDC side, which I don't think is happening yet, so I'm planning on dual-purposing this counter for interrupt checks when I get to fleshing out interrupt handling.
* The LVDC documentation claims that for MPY, the partial product of the multiplicand with the lower 12 bits of the accumulator is available to the 2nd instruction following the MPY. It turns out this is true, but not in the way we initially thought. This product is formed as though those lower 12 bits were the _most_ significant bits …

yaLVDC: Corrections for MPY partial products and DIV

---

yaDSKYb1/Makefile
yaDSKYb1/yaDSKYb1-widgetized.cpp
yaDSKYb1/yaDSKYb1.cpp

This fixes several inaccuracies and other issues with yaDSKYb1, found when developing my own Block I AGC emulator:
- The COMP FAIL light illuminates instead of the COMP ACTY light
- The SCALER FAIL light illuminates instead of the TM FAIL light
- The flashing pace of the Verb/Noun display was too slow, documentation stating "roughly once per second" was exaggerating: it's actually the FS17 timing signal from the scaler, which has a frequency of 0.78125 Hz, or a period of 1.28 seconds (640 ms on, 640 ms off).
- Launching the program would display a warning message about an incorrect grid sizer alignment object.
- There was an unnecessary 200 ms delay in part of the packet-sending code (recommended to remove by @thewonderidiot )

yaDSKYb1 Fixes

---

yaAGC/agc_engine.c

There's been an elusive longstanding bug seen in NASSP where the AGC would fail to correctly exit standby mode. Instead of sending the user to a flashing V37, the computer would instead pick right back up at the pre-standby V50 N25 display, sometimes accompanied by a RESTART light. This failure to come out of standby mode meant the clocks weren't updated with elapsed time from the scaler, and sometimes seemingly led to weird behavior we couldn't really explain.
@indy91 and I finally tracked it down a couple of days ago. It turns out that our simulation of hardware restarts (including standby entry) through the GOJAM signal was complete per the hardware-level description in [Digital Development memo 340](https://www.ibiblio.org/apollo/Documents/dd_memo_340.pdf), but neglected to reset …

yaAGC: Clear more internal state on GOJAM

---

yaAGC/NullAPI.c
yaAGC/SocketAPI.c
yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaAGC/agc_engine_init.c
yaAGC/ringbuffer_api.c

RADARUPTs are somewhat unique in the AGC in that unlike other interrupts for external hardware, all of the timing for the interrupt and the actual generation of the interrupt occurs entirely within the AGC. Strictly speaking, no hardware even needs to be attached to the computer for a radar cycle to complete and a RADARUPT to be generated.
It turns out that certain ropes, especially Skylark, are very sensitive to the exact timing of this interrupt. If they appear too early or too late, it's possible to get program alarms, or even for running programs to silently break and become completely non-functional. As such, I think it makes sense to add accurate RADARUPT simulation to yaAGC.
The timing for the interrupt presented in this PR is as accurate as I can get it without deeper changes to …

yaAGC: Implement internally-timed RADARUPTs

---

README.md

I was confused how to run the simulator and had to fiddle with the VirtualAGC/VirtualAGC binary and paths to make it work, hopefully this will prevent others from going through the same process.

update README.md with correct paths and instructions to build for linux

---

yaAGC/agc_engine.c

Prints messages when the master alarm is triggered, and indicates what the type of the alarm.
Several alarms are reboots are silently being triggered in [example code](https://www.ibiblio.org/apollo/DIY.html#Bare-Metal_Programming).  Raising visibility of them is a prerequisite in either fixing the example code, or else fixing the AGC if the alarms are not correctly firing.

Add Alarm Messages

---

VirtualAGC/VirtualAGC.cpp

This one line requires wxWidgets 3.1.4
Removing it allows existing 3.0 installations to continue to work.
Raspberry Pi OS (5.10 Buster) doesn't seem to have an apt upgrade path for > 3 at the moment.
Given that this is just a debugging line, I think the costs outweigh the value.
```
VirtualAGC.cpp: In member function ‘bool VirtualAGC::FormTiling()’:
VirtualAGC.cpp:3040:44: error: ‘class VirtualAGC’ has no member named ‘GetDPIScaleFactor’; did you mean ‘GetContentScaleFactor’?
printf("DPI scale factor: %g\n", this->GetDPIScaleFactor());
^~~~~~~~~~~~~~~~~
GetContentScaleFactor
make[1]: *** [Makefile:215: VirtualAGC] Error 1
make[1]: Leaving directory '/home/pi/virtualagc/VirtualAGC'
make: *** [Makefile:610: VirtualAGC] Error 2
```

Restore compatibility with wxWidgets 3.0
