virtualagc/virtualagc

.gitignore
Makefile

Protecting more GUI programs with `ifndef NOGUI`.

Toplevel Makefile cleanup

---

yaYUL/yaYUL.c

These are the tweaks I've had to make to yaYUL to make my hardware simulations work. Parity bit calculation is straightforward.
As for bank order, I'm guessing that banks 2 and 3 come first in the listings simply by developer preference of showing fixed-fixed memory first. I'm basing this off of [the block of gates in the middle-right of page 2 of the Rupt Service Module](http://klabs.org/history/ech/agc_schematics/logic/a15-2.jpg). This uses the fixed address bits [calculated on page 1 of the module](http://klabs.org/history/ech/agc_schematics/logic/a15-1.jpg) to determine which of the three ropes (R, S, or T), which of the two modules for that rope (high or low), and then roughly speaking which third of the strands in that module the address is on. 
Here is that same block of gates, …

yaYUL: Add flag for hardware bank ordering (0,1,2,3 vs. 2,3,0,1) and parity calculation

---

yaAGC/agc_engine.c

In theory this should make handling of TIME6 much more accurate, and fix #46. Rationale for the changes:
T6P, the counter pulse that generates a counter request on TIME6, can only occur if T6ON is set via CH13 bit 15. If not set, TIME6 cannot increment.
T6ON, in turn, is cleared when T6RPT is triggered.
T6RPT requests are generated when a ZOUT pulse is emitted for counter 31, AKA TIME6 (the other two inputs on that gate are counter addressing)
And lastly, a quick look at the sim, on the DINC *before* ZOUT occurs and T6RUPT is generated:
The control pulses generated by the sim match what is described by Hugh Blair-Smith in his Memo#9:
```
DINC
1. xx  RSCT   WS
2. xx  RSC    WG
5. xx  RG     WY     TSGN   TMZ    TPZG
6. 00  MONEX  POUT
6. 10  PONEX  MOUT
6. x1         ZOUT
7. xx  RU     WSC …
```

Updated handling of TIME6 and T6RUPT. Hopefully fixes #46.

---

yaAGC/agc_engine.c

The NASSP guys are still having program alarms from multiple things attempting to use the radars at once. I took a look at timer phasing to see if things might be running at the wrong relative times, and discovered that TIME4 and TIME5 both have the wrong phasing.
First, I switched from PINCing SCALER1 and SCALER2 to just straight incrementing them. Those channels are direct views into the [flip-flops in the center of every clock divider in the Scaler module](http://klabs.org/history/ech/agc_schematics/logic/a01-1.jpg), and don't need CPU time to change states.
For timer phasing, counter increment requests are generated by the following circuit in Inout IV, page 2:
TIME1 and TIME3 both increment every F10B pulse, whereas TIME5 increments every F10A pulse. F10 is the 100Hz frequency, and …

Change TIME5 to be phased 5ms after TIME3, and TIME4 to be phased 7.5ms after TIME3

---

.gitignore
Aurora12/DOWN_TELEMETRY_PROGRAM.agc

Task84 down telemetry program 370 376

---

Aurora12/ASCENT_INERTIA_UPDATER.agc

Completed the Transcription of the ASCENT_INERTIA_UPDATER section

Transcription of ASCENT_INERTIA_UPDATER.agc

---

Aurora12/CONTROLLER_AND_METER_ROUTINES.agc

After manual transcription, did a yaYUL --format.

Transcribed pages 368-569. Resolves #83.

---

Aurora12/INTER-BANK_COMMUNICATION.agc

Transcription for INTER-BANK COMMUNICATION. Completes #66.

Aurora 12: Filled out INTER-BANK COMMUNICATION

---

Aurora12/EXECUTIVE.agc

Resolves #69
Used the corresponding file from Lumiary099 as a guide, but the changes were
extensive enough that it wasn't very helpful.

Transcribed pages 126-138, EXECUTIVE.agc

---

Aurora12/AGC_BLOCK_TWO_SELF-CHECK.agc

#85: Transcribed AGC BLOCK TWO SELF-CHECK

---

Aurora12/LIST_PROCESSING_INTERPRETER.agc

how about task #89 IMU PERFORMANCE TESTS 1 as next one?
I might make sense to assign the whole IMU set to me in one shot i.e. Task #89 - 92

LIST_PROCESSING_INTERPRETER.agc finalized

---

Aurora12/LEM_FLIGHT_CONTROL_SYSTEM_TEST.agc

Aurora 12: transcribed LEM FLIGHT CONTROL SYSTEM TEST.

---

Colossus249/Apollo 7 Rendezvous.readme

Here my first attempt at a readme for the Apollo 7 rendezvous core dump. I found it a little bit difficult how much knowledge to expect from the reader. I guess the most important part are the step-by-step instructions for the DSKY inputs.

Readme for Apollo 7 rendezvous core dump

---

Aurora12/IMU_PERFORMANCE_TESTS_2.agc

How about task #96 Transcribe Q,R-AXES REACTION CONTROL SYSTEM AUTOPILOT
as next one

Task90 imu performance tests 475 499

---

Aurora12/OPTIMUM_PRELAUNCH_ALIGNMENT_CALIBRATION.agc

Filled out OPTIMUM PRELAUNCH ALIGNMENT CALIBRATION

---

Aurora12/AOTMARK.agc
Aurora12/INTERRUPT_LEAD_INS.agc
Aurora12/KEYRUPT_UPRUPT.agc
Aurora12/SINGLE_PRECISION_SUBROUTINES.agc

and minor updates to others, mostly adding page numbers in the comment section.

SP SUBS and INTERRUPT LEAD INS

---

Aurora12/AOSTASK.agc
Aurora12/CONTROLLER_AND_METER_ROUTINES.agc
Aurora12/KALMAN_FILTER_FOR_LEM_DAP.agc
Aurora12/OPTIMUM_PRELAUNCH_ALIGNMENT_CALIBRATION.agc

At this momnt only undefined EB/FB values and locations remain

Fix unrecognized opcodes and some messed up comments

---

Aurora12/IMU_MODE_SWITCHING_ROUTINES.agc

Aurora 12: Transcribed IMU MODE SWITCHING ROUTINES

---

Aurora12/Q,R-AXES_REACTION_CONTROL_SYSTEM_AUTOPILOT.agc

I'll take task #97 JET FAILURE CONTROL LOGIC as next one

Task96 q r axes reaction control system autopilot 562 593

---

Aurora12/TRIM_GIMBAL_CONTROL_SYSTEM.agc

Aurora 12: filled out TRIM GIMBAL CONTROL SYSTEM

---

Aurora12/TRIM_GIMBAL_CONTROL_SYSTEM.agc

Creates a number of double defined labels

Looks like code but is actually documentation

---

Aurora12/ERASABLE_ASSIGNMENTS.agc
Aurora12/FRESH_START_AND_RESTART.agc
Aurora12/INTERRUPT_LEAD_INS.agc
Aurora12/KALMAN_FILTER_FOR_LEM_DAP.agc
Aurora12/LIST_PROCESSING_INTERPRETER.agc

if you want yo can assign #106  to me. I obviously have started doing it anyways.
Block 3 is already clean

some missing instructions and typos

---

Aurora12/AOSTASK.agc
Aurora12/ASCENT_INERTIA_UPDATER.agc
Aurora12/DOWN_TELEMETRY_PROGRAM.agc
Aurora12/IMU_PERFORMANCE_TESTS_1.agc
Aurora12/JET_FAILURE_CONTROL_LOGIC.agc
Aurora12/P-AXIS_REACTION_CONTROL_SYSTEM_AUTOPILOT.agc
Aurora12/PHASE_TABLE_MAINTENANCE.agc
Aurora12/Q,R-AXES_REACTION_CONTROL_SYSTEM_AUTOPILOT.agc
Aurora12/RCS_FAILURE_MONITOR.agc
Aurora12/TRIM_GIMBAL_CONTROL_SYSTEM.agc

First set of corrections. There are more checks and updates needed when code  transcription is completed.
There are also BLK2 yaYul updates needed. see #104.

Task106 proof completed transcription part1

---

Aurora12/INFLIGHT_ALIGNMENT_ROUTINES.agc

Completed Transcription Issue #86

Transcription of Aurora 12 - Inflight Alignment Routines

---

Sunburst120/INTERPRETER.agc

Transcription of Sunburst 120 INTERPRETER

---

Sunburst120/206_SERVICE_ROUTINES.agc

Closes #221.
Man, this was tough. I've posted a full listing of all of the instructions I had to disassemble to the issue. I was able to recover one comment from SHEPATIN, and a few more from Colossus 237. The rest are lost until we find another copy of Sunburst 120...

Sunburst 120: Transcribed/disassembled 206 SERVICE ROUTINES.

---

Aurora12/ALARM_AND_ABORT.agc

Aurora 12: Transcribed ALARM AND ABORT.

---

Aurora12/RADAR_TEST_PROGRAMS.agc

Aurora 12: Adapted RADAR TEST PROGRAMS from Sunburst 120

---

Sunburst120/KALMAN_FILTER_FOR_LM_DAP.agc

Largely adapted from Aurora 12.

Sunburst 120: Transcribed KALMAN FILTER FOR LM DAP

---

Sunburst120/AOSTASK_AND_AOSJOB.agc

Sunburst 120: Transcribed AOSTASK AND AOSJOB

---

Aurora12/RADAR_LEAD-IN_ROUTINES.agc

Only the code. The comments still require updating, i.e. there will be a second pull request.

Task77 radar lead in routines

---

Aurora12/EXTENDED_VERBS.agc

Only the code. The comments still require updating, i.e. there will be a second pull request.

The code. Comments still to come

---

Sunburst120/SPS_BACK-UP_RCS_CONTROL.agc

Sunburst 120: Transcribed SPS BACK-UP RCS CONTROL.

---

Sunburst120/ATTITUDE_MANEUVER_ROUTINE.agc

Sunburst 120: Transcribed ATTITUDE MANEUVER ROUTINE.

---

Sunburst120/GIMBAL_LOCK_AVOIDANCE.agc

Sunburst 120: Transcribed GIMBAL LOCK AVOIDANCE.

---

Sunburst120/KALCMANU_STEERING.agc

Sunburst 120: Transcribed KALCMANU STEERING.

---

Luminary210/SUBROUTINE_CALLS.agc

Shouldn't this actually be created by yaYul??

SUBROUTINE_CALLS

---

Luminary210/FLAGWORD_ASSIGNMENTS.agc
Luminary210/FRESH_START_AND_RESTART.agc

Fix typo in FLAGWORD_ASSIGNMENTS

FRESH_START_AND_RESTART

---

Luminary210/KALMAN_FILTER.agc

Transcribed and formatted KALMAN_FILTER.agc (pages 1468-1469)
Solves issue #367

KALMAN_FILTER (#367)

---

Luminary210/KEYRUPT,_UPRUPT.agc

Transcribed and formatted KEYRUPT,_UPRUPT.agc (pages 1335 - 1337).
Solves issue #355

KEYRUPT,_UPRUPT transcribed

---

Luminary210/DAP_INTERFACE_SUBROUTINES.agc

First crack at this. Would be keen to do more, please let me know any problems with this one, cheers

transcribed pages 1403-1406 - DAP INTERFACE SUBROUTINES

---

Luminary210/AOTMARK.agc
Luminary210/ERASABLE_ASSIGNMENTS.agc
Luminary210/SYSTEM_TEST_STANDARD_LEAD_INS.agc

Has also some fixes for typos in AOTMARK.agc and ERASABLE_ASSIGNMENTS.agc

Task306 system test standard lead ins

---

Luminary210/ERASABLE_ASSIGNMENTS.agc
Luminary210/IMU_PERFORMANCE_TESTS_2.agc

Fix typo in ERASABLE_ASSIGNMENTS.agc

IMU_PERFORMANCE_TESTS_2

---

Luminary210/GROUND_TRACKING_DETERMINATION_PROGRAM_-_P21.agc
Luminary210/P34-P35,_P74-P75.agc

fix typo in GROUND_TRACKING_DETERMINATION_PROGRAM_-_P21 and remove TABS

P34-P35,_P74-P75

---

Luminary210/BURN,_BABY,_BURN_--_MASTER_IGNITION_ROUTINE.agc
Luminary210/P76.agc
Luminary210/R31.agc

also fix typo and omission in P76.agc

Task321 burn baby burn

---

Luminary210/FINDCDUW_-_GUIDAP_INTERFACE.agc
Luminary210/RTB_OP_CODES.agc

Add missed SETLOC in RTB_OP_CODES.agc

FINDCDUW_-_GUIDAP_INTERFACE

---

Luminary210/AOSTASK_AND_AOSJOB.agc
Luminary210/ASCENT_GUIDANCE.agc
Luminary210/DISPLAY_INTERFACE_ROUTINES.agc
Luminary210/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc
Luminary210/P12.agc
Luminary210/THROTTLE_CONTROL_ROUTINES.agc

Task369 aostask and aosjob

---

Luminary210/ASCENT_GUIDANCE.agc
Luminary210/BURN,_BABY,_BURN_--_MASTER_IGNITION_ROUTINE.agc
Luminary210/CONTROLLED_CONSTANTS.agc
Luminary210/LANDING_ANALOG_DISPLAYS.agc
Luminary210/LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES.agc
Luminary210/P12.agc
Luminary210/P40-P47.agc
Luminary210/PINBALL_NOUN_TABLES.agc
Luminary210/Q,R-AXES_RCS_AUTOPILOT.agc
Luminary210/SERVICER.agc

There are 6 binary differences remaining. They all look like the need for a SUPERBANK workaround is needed and the consequential wrong bugger word.

Task365 q r axes rcs autopilot

---

Luminary069/P34-P35,_P74-P75.agc
Luminary069/S-BAND_ANTENNA_FOR_LM.agc

fix some typos

---

Luminary069/INTERRUPT_LEAD_INS.agc

INTERRUPT_LEAD_INS

---

Luminary069/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc
Luminary069/P12.agc
Luminary069/THROTTLE_CONTROL_ROUTINES.agc

LUNAR_LANDING_GUIDANCE_EQUATIONS

---

Luminary069/DOWNLINK_LISTS.agc
Luminary069/ERASABLE_ASSIGNMENTS.agc

DOWNLINK_LISTS

---

Luminary116/FIXED-FIXED_CONSTANT_POOL.agc
Luminary116/GROUND_TRACKING_DETERMINATION_PROGRAM_-_P21.agc

Resolves issues #680 and #701.
Both files have been updated to match the Luminary 116 scans.

Update FIXED-FIXED_CONSTANT_POOL.agc + GROUND_TRACKING_DETERMINATION_PROGRAM_-_P21.agc

---

Luminary116/FRESH_START_AND_RESTART.agc
Luminary116/PHASE_TABLE_MAINTENANCE.agc
Luminary116/RADAR_LEADIN_ROUTINES.agc

I Think the reconstruction of the missing pages went well. I don't see any address shifts and on binary level it looks as if all detected differences are due to shifted label addresses and not opcodes.
I suggest to merge this part in but leave the task open as part of task#735 for the final code verification.

Task659 fresh start and restart

---

Luminary116/ALARM_AND_ABORT.agc
Luminary116/DAPIDLER_PROGRAM.agc
Luminary116/THROTTLE_CONTROL_ROUTINES.agc

THROTTLE_CONTROL_ROUTINES

---

Luminary116/RCS_FAILURE_MONITOR.agc

It's hanging there for three weeks now. No code changes just some reformatting of comments.

RCS_FAILURE_MONITOR

---

Luminary116/AOSTASK_AND_AOSJOB.agc
Luminary116/ASCENT_GUIDANCE.agc
Luminary116/BURN,_BABY,_BURN_--_MASTER_IGNITION_ROUTINE.agc
Luminary116/CONIC_SUBROUTINES.agc
Luminary116/DOWN-TELEMETRY_PROGRAM.agc
Luminary116/ERASABLE_ASSIGNMENTS.agc
Luminary116/EXTENDED_VERBS.agc
Luminary116/FRESH_START_AND_RESTART.agc
Luminary116/IMU_COMPENSATION_PACKAGE.agc
Luminary116/IMU_MODE_SWITCHING_ROUTINES.agc
Luminary116/INTEGRATION_INITIALIZATION.agc
Luminary116/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc
Luminary116/P-AXIS_RCS_AUTOPILOT.agc
Luminary116/P20-P25.agc
Luminary116/P51-P53.agc
Luminary116/P70-P71.agc
Luminary116/P76.agc
Luminary116/PINBALL_NOUN_TABLES.agc
Luminary116/S-BAND_ANTENNA_FOR_LM.agc
Luminary116/SERVICER.agc
Luminary116/SERVICE_ROUTINES.agc
Luminary116/THE_LUNAR_LANDING.agc
Luminary116/TJET_LAW.agc
Luminary116/UPDATE_PROGRAM.agc
Luminary116/WAITLIST.agc

No binary differences detected any longer using yaYul as well as JaYul

Task735 correct code errors

---

yaAGC/agc_engine.c
yaAGC/agc_engine.h
yaAGC/agc_engine_init.c

@indy91, here are changes to move all of the things NASSP had made non-static, as well as the new DSKY channel 163 stuff, into agc_t. I've run the Aurora tests on it and everything still seems to be operational. Let me know how it works in NASSP. :smile:

Moved a bunch of static things from agc_engine.c into agc_t

---

Sunburst37/ERASABLE_ASSIGNMENTS.agc
Sunburst37/RADAR_TEST_PROGRAMS.agc

and fix for RUPTSTOR in ERASABLE_ASSIGNMENTS

RADAR_TEST_PROGRAMS

---

Sunburst37/WAITLIST.agc

Transcribe WAITLIST

---

Sunburst37/INTER-BANK_COMMUNICATION.agc

Transcribe INTER-BANK_COMMUNICATION

---

Sunburst37/ERASABLE_ASSIGNMENTS.agc
Sunburst37/THRUST_MAGNITUDE_FILTER.agc
Sunburst37/THRUST_MISSION_CONTROL_PROGRAM_TJS.agc

THRUST_MAGNITUDE_FILTER

---

Sunburst37/AGC_BLOCK_TWO_SELF-CHECK.agc
Sunburst37/KALMAN_FILTER_FOR_LM_DAP.agc
Sunburst37/LMP_COMMAND_ROUTINES.agc

and two fixes for EXTEND instructions

LMP_COMMAND_ROUTINES

---

Sunburst37/MISSION_PHASE_2_GUIDANCE_REFERENCE_RELEASE_PLUS_BOOST_MONITOR.agc
Sunburst37/TUMBLE_MONITOR.agc

TUMBLE_MONITOR

---

Sunburst37/AOSTASK_AND_AOSJOB.agc
Sunburst37/FIND_CDU_DESIRED.agc
Sunburst37/LAMB.agc
Sunburst37/MP4-CONTINGENCY_ORBIT_INSERTION.agc
Sunburst37/MP_7_-_SIVB_LEM_SEPARATION.agc

FIND_CDU_DESIRED

---

Sunburst37/AS206_MISSION_SCHEDULING_PACKAGE.agc
Sunburst37/ASCENT_STEERING.agc
Sunburst37/DAP_INTERFACE_SUBROUTINES.agc
Sunburst37/EXTENDED_VERBS.agc
Sunburst37/FRESH_START_AND_RESTART.agc
Sunburst37/IMU_COMPENSATION_PACKAGE.agc
Sunburst37/INTERPRETER.agc
Sunburst37/MISSION_PHASE_11_-_DPS2_FITH_APS1.agc
Sunburst37/MP_3_-_SUBORBITAL_ABORT.agc
Sunburst37/OPTIMUM_PRELAUNCH_ALIGNMENT_CALIBRATION.agc
Sunburst37/P-AXIS_REACTION_CONTROL_SYSTEM_AUTOPILOT.agc
Sunburst37/PREBURN_FOR_APS2.agc
Sunburst37/Q,R-AXES_REACTION_CONTROL_SYSTEM_AUTOPILOT.agc
Sunburst37/RCS_FAILURE_MONITOR.agc
Sunburst37/RESTART_TABLES_AND_RESTARTS_ROUTINE.agc
Sunburst37/SECOND_DPS_GUIDANCE.agc
Sunburst37/T4RUPT_PROGRAM.agc
Sunburst37/TRIM_GIMBAL_CONTROL_SYSTEM.agc
Sunburst37/WAITLIST.agc

Fix mainly my own typos.
FYI: there are many errors with regard to 2CADR/BBCON and the SBANK bits

Fix typos 3

---

Zerlina56/AGS_INITIALIZATION.agc

Zerlina56: Transcribe AGS_INITIALIZATION

---

Scripts/normalizeLEMUnpunchHtml.py

This is a slight modification of the normalizeUnpunchHtml.py script

add modified script for LEM technical drawings.

---

CMakeLists.txt
yaYUL/CMakeLists.txt

would perhaps help make building on many platforms easier, as that is the *raison d'être* of CMake.
I just built one target here to show how it would look-the top-level CMakeLists.txt invoking each directory and target.

introducing CMake

---

CMakeLists.txt
jWiz/CMakeLists.txt
yaAGC/CMakeLists.txt
yaAGS/CMakeLists.txt
yaDSKY2/CMakeLists.txt
yaLEMAP/CMakeLists.txt
yaTelemetry/CMakeLists.txt
yaUniverse/CMakeLists.txt
yaUplinkBlock1/CMakeLists.txt

added targets 
yaTelemetry
yaUniverse
yaUplinkBlock1
jWiz

Cmake: add more targets

---

yaAGCb1/executeOneInstruction.c

These are fixes for yaAGCb1 to make it able to run Solarium 55's SELF-CHECK. Details are in #1150.

yaAGCb1: Fixed a few errors identified by SELF-CHECK

---

PTC-ADAPT-Self-Test-Program/Makefile
yaASM.py/yaASM.py
yaASM.py/yaASMdefineMacros.py
yaASM.py/yaASMerrors.py
yaASM.py/yaASMpreprocessor.py

While not fully working, is working much, much better than what was on the main branch.

Refactor ya asm

---

yaLVDC/runOneInstruction.c

Division in the LVDC can give some slightly-off results, especially when negative signs are involved. For example, 00000000 / 377777777 = 377777774. In an attempt to achieve perfect agreement with the hardware simulation, I've replaced the implementation of DIV in yaLVDC with the modified nonrestoring division algorithm used in hardware.
This implementation is able to pass [all of the DIV self-tests I've put together so far](https://github.com/thewonderidiot/lvdc_simulation/blob/71cdd6f6606d72d1af834beb1d43bbedfdaf158a/self-test/self-test.lvdc#L1231).

yaLVDC: Simulate the hardware algorithm for DIV

---

yaLVDC/runOneInstruction.c

Various small fixes to get EXM working. It now passes all of the self-tests I put together for EXM [here](https://github.com/thewonderidiot/lvdc_simulation/blob/4761f511a5dd1e646d059d59f4f5c194326ec1d1/self-test/self-test.lvdc#L1382).

yaLVDC: Fix implementation of EXM

---

yaLVDC/processInterruptsAndIO.c
yaLVDC/runOneInstruction.c
yaLVDC/yaLVDC.h

This PR contains a lot of tweaks, resulting from a pretty deep rabbit hole of adding a very simple (timers-only) LVDA implementation and getting interrupt behavior to match the hardware sim. Here's a rundown of what all has changed, and what I've learned about the LVDA.
Document sources are:
- [Laboratory Maintenance Instructions for LVDA, Volume 1: Description and Theory](https://www.ibiblio.org/apollo/Documents/19730064316_1973064316.pdf) - this document is frustratingly incomplete and lacks many theory-of-operation sections. Things not covered include interrupts, the RTC, and timers (i.e. almost everything that I care about in this PR).
- [Laboratory Maintenance Instructions for LVDA, Volume 2: Maintenance Data](https://www.ibiblio.org/apollo/Documents/LaboratoryMaintenanceInstructionsF …

yaLVDC: Add preliminary LVDA support, and refactor interrupts

---

yaLVDC/runOneInstruction.c

This was a subtle bug that I found by pure luck. EXM's `goto reenterForEXM;` was bypassing both the PQR result and interrupt inhibit countdown timers. This means that if you have the instruction sequence
```
MPY   A
EXM   0,1,0
STO   B
CLA   775
```
before this fix, yaLVDC would not have the final product ready in 775 yet, even though it should.
It turns out that the AS-512 software uses precisely this sequence of instructions when constructing critical guidance matrices. After fixing this bug, yaLVDC is now capable of achieving a stable orbit in the AS-512 flight program's repeatable flight simulation mode, when started with this simple preflight program:
```
ORGDD   0,0,0,000,0,0,0
E.PP1  CDS     D.LEID
CLA     D.KB11
STO     D.FMDI
HOP     E.GP0
```

yaLVDC: Fix EXM such that its second cycle decrements counters

---

yaLVDC/yaLVDC.c

yaLVDC: Make LVDC start execution at 000 like PTC

---

yaAGC/agc_engine.c

As discovered by @NeilFraser in #1230, our current implementation of the TC Trap hardware alarm has a bug, that was introduced while attempting to simulate the (different) actual hardware bug.
The TC Trap alarm has two halves:
1. _Only_ TCs or TCFs are executed within a given interval. In the hardware design, this is implemented by checking the state of the `TC0` and `TCF0` nets during timepulse `T04`. If neither instruction is selected, the alarm is reset. This works on hardware, but because of this bug is currently partly broken in yaAGC.
2. _No_ TCs or TCFs are executed within a given interval. This half is fundamentally flawed in the original hardware design because `TC0` and `TCF0` are sampled continuously instead of at a specific time. Any brief transients on TC0 or TCF0, which are …

yaAGC: Differentiate between real TC/TCFs and transients for TC Trap
